Feature/concurrency
madeindjs/spider pull request #9
Opened 2021-04-05 00:30 UTC by Dragnucs

2021-04-06 22:46 UTC, Dragnucs commented
Hello @madeindjs !

This PR uses the library Rayon to handle thread pools since it is well maintained, has recent commits and merged PRs, is old enough, and has a large user base. It also moves the code a bit more functional style to avoid bugs that went unnoticed like duplicate page fetching and parsing.

I stay available for any comments.

2021-04-11 18:48 UTC, madeindjs requested changes
Really great work! Thank you. I just emit a simple suggestion. Thank you

2021-04-11 18:48 UTC, madeindjs commented on src/configuration.rs
> +            user_agent: "spider/1.2.1",
Can you use 

```rs
const VERSION: &'static str = env!("CARGO_PKG_VERSION");
```

See [How can a Rust program access metadata from its Cargo package? - Stack Overflow](https://stackoverflow.com/questions/27840394/how-can-a-rust-program-access-metadata-from-its-cargo-package)

2021-04-11 21:02 UTC, Dragnucs commented on src/configuration.rs
> +            user_agent: "spider/1.2.1",
It turns out that the simplest tasks are the more difficult. I just don't know how to concatenate two strings.
I don't know what is happening, but string concatenation in Rust is more complicated than thread safety, parralelism and passing closures.

2021-04-12 12:06 UTC, madeindjs commented on src/configuration.rs
> +            user_agent: "spider/1.2.1",
Ok so I moved it in issue #11

2021-04-12 12:06 UTC, merged